# Generated by Django 6.0.3 on 2026-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentModule', '0002_alter_comment_options_rename_user_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
