# Generated by Django 6.0.3 on 2026-03-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentModule', '0003_remove_comment_author_comment_author_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user_id')},
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
