# Generated by Django 6.0.3 on 2026-03-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentModule', '0004_alter_like_unique_together_like_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
