# Generated by Django 5.2.6 on 2026-02-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
